title: "Gwen Maudet"
description: "Postdoctoral Researcher | University of Luxembourg"
baseurl: ""
url: "https://gwenmaudet.github.io"
theme: minima
author: Gwen Maudet
email: gwen.maudet@imt-atlantique.fr

# Optional: Navigation links (for custom layouts or future theme upgrade)
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
  - title: "Experience"
    url: /experience/
  - title: "Contact"
    url: /contact/

markdown: kramdown
show_excerpts: true

# Minima theme config (for better academic look)
minima:
  skin: classic
  social_links: []
  # You can add orcid, scholar, linkedin here later

# Github Pages compatibility (do not add plugins unless you know they are supported)
